### ISSUE TITLE
Playback window: Steps not recording 

### ISSUE THREAD

**Issue by Samyak109** [SeleniumHQ/selenium-ide#1722]
## 🐛 Bug Report

While I am starting recording from the Project Editor, Playback windows open but the steps that we perform are not recorded and shown as commands on project editor window.

## To Reproduce

1. Click on new project from the splash window.
2. Create a new test and then click on start record button
3. You will notice when we are recording the steps, those are not getting captured on the project editor

## Expected behavior

All the actions should get recorded and when we close the playback window, close command should also get recorded

Error:
11:12:33 AM [info] [
  TypeError: Cannot read properties of undefined (reading 'opensWindow')
      at c.getWinHandleId (Local\Programs\@seleniumhqselenium-ide\resources\app.asar\build\webpack:\src\main\session\controllers\Recorder\index.ts:144:16)
      at process.result (node:internal/process/task_queues:95:5)
      at result (Local\Programs\@seleniumhqselenium-ide\resources\app.asar\build\webpack:\src\main\api\classes\RawHandler.ts:52:13)
      at IpcMainImpl.<anonymous> (Local\Programs\@seleniumhqselenium-ide\resources\app.asar\build\webpack:\src\main\api\classes\RawHandler.ts:72:13)
]
11:12:33 AM [info] [ '- -' ]
## Environment

OS: Windows 10
Selenium IDE Version:  Selenium.IDE.Setup.4.0.0-alpha.49
Browser:
Browser Version: Chrome Version 117.0.5938.150 (Official Build) (64-bit)

**Comment by toddtarsi** [comment]
Oh no! I'll take a look this weekend. Sorry about that!

**Comment by toddtarsi** [comment]
@Samyak109 - Sorry for the delay, all issues here should be resolved. Thank you for testing it. I'm going to start a beta release branch soon of vetted versions, so users aren't directed by default onto latest / unstable.

**Comment by toddtarsi** [comment]
@Samyak109 - You'll want to download v.51

**Comment by Samyak109** [comment]
Thanks @toddtarsi  for quick resolution

**Comment by Samyak109** [comment]
The problem still exists for me. Opening another issue with the logs attached. @toddtarsi
