### ISSUE TITLE
¿bug or feature? Selenium IDE window does not remember its position

### ISSUE THREAD

**Issue by BartolomeSintes** [SeleniumHQ/selenium-ide#1787]
## 🐛 Bug Report

In Windows, when you reopen an application, the window position and size is usually the same of the last time you closed the application. Selenium IDE alpha 83 behaved that way, but Selenium IDE alpha 97 always open in the same position.

I do not know if this change of behavior is intended or not.

## To Reproduce

1. Open Selenium
2. Load a project
3. Move the window
4. Close Selenium
5. Open Selenium
6. The window opens in the same place, not in the place the first window was moved to

## Expected behavior

I would expect the window opened where the previous was closed.
I have two monitors and I would like Selenium to open automatically in the second screen and not have to move it manually.

## Environment

OS:  Windows 10
Selenium IDE Version:  4.0.1 alpha 97

**Comment by toddtarsi** [comment]
@BartolomeSintes - Should be fixed in v97? Let me know your experience 🤞

**Comment by toddtarsi** [comment]
*98 I mean

**Comment by ms6073** [comment]
Nope - at least with Windows 11 (see screen shot below). Also note that the installer is not able to update an existing Alpha install, thus I first have to uninstall, then reinstall, but even after launching and resizing the app (multi-monitor setup), still not remembering the size or position.

![image](https://github.com/SeleniumHQ/selenium-ide/assets/30844608/818dead5-9d59-4266-84a8-2aec74bb44d5)

**Comment by toddtarsi** [comment]
@ms6073 - Ah! Is that the default of how its showing up?!? That's terrible :(

And yeah, I know about the terrible install process. I'm sorry, installing and updating will be worlds better once I get code signing certificates

You wouldn't believe how hard it is to get anything that requires money out of an open source committee 😭

**Comment by BartolomeSintes** [comment]
alpha 98 still suffers this problem in Windows 10.
I have seen the same problem commented by @ms6073 (a very narrow window), but I am not sure if the problem is related to a low display resolution (1024 * 768) or related to the fact of having two screens with different display resolutions (Full HD vs 1024 * 768).

**Comment by ms6073** [comment]
> I am not sure if the problem is related to a low display resolution (1024 * 768) or related to the fact of having two screens with different display resolutions (Full HD vs 1024 * 768).
My dual monitor setup enjoys the same resolution on both monitors ( 2560 x 1440 ) but I am opening the app on the second/non-primary monitor..
