### ISSUE TITLE
Add API methods in Selenium IDE to trigger certain actions

### ISSUE THREAD

**Issue by cdifino** [SeleniumHQ/selenium-ide#780]
## 🚀 Feature Proposal
Add API methods to Selenium IDE that trigger certain events (such as opening the extension) when these methods are called from an external source. 

## Motivation

I want to automatically open Selenium IDE when I perform certain action in my project. In other words, I want to enable communication between an external application and Selenium-IDE. 

## Example

I have an application that has a "Create Test" Button. When this button is clicked I want to be able to send a message to the extension so it can open Selenium IDE and start creating a new test. 

This is one of the many use cases of enabling this type of communication. Whenever I have more use cases we can discuss them in a future. A good starting point is to be able to open the extension from an API call.

**Comment by corevo** [comment]
How would you like to automate this, meaning, who should be able to send that API call?

**Comment by cdifino** [comment]
So I think you already have some methods to communicate across extensions (background.js - OnMessageExternal). So  we could extend on this work and just accept extensions to communicate with Selenium-IDE

**Comment by corevo** [comment]
You want to extend the plugin API then? we can spec it out.

What exactly were you thinking?

**Comment by cdifino** [comment]
Yes, the main two functionalitites that we would like are: 
**1. The ability to open SeleniumIDE from another extension and load a project if it contains one.** The idea would be to send a message like:   chrome.runtime.sendMessage("mooikfkahbdckldjjndioackbalphokd", {
  uri: "/project",
  verb: "post",
  payload: { //some side file json} 
}, res=>console.log(JSON.stringify(res)));
});
The background of the extension will be listening for this external message and if received, will open selenium IDE and load the project contained in the payload (if it contains one).

**2. The ability to make a call to SeleniumIDE to start recording.**
Send a post message to a different uri, when the background receives this message, it starts a new project in SeleniumIDE and starts recording.

**Comment by corevo** [comment]
I like it, feel free to send a PR for these, make sure to document the change as well in the docs.

Just a few pointers
1. Overall the API service is down, since the IDE is closed, therefore I would rather plugins send a different type of message
```js
chrome.runtime.sendMessage("mooikfkahbdckldjjndioackbalphokd", {
startSideIfClosed: true
}, res=>console.log(JSON.stringify(res)));
});
```
And then also add an API endpoint to load a project
```js
chrome.runtime.sendMessage("mooikfkahbdckldjjndioackbalphokd", {
uri: "/project",
verb: "post",
payload: { //some side file json}
}, res => {
 // boolean if the project was loaded or not
});
});
```
When a plugin tries to access this endpoint Selenium IDE should show a dialog telling the user:
`{plugin name} is trying to load a project`, and the user will have to accept or decline. 

2. I don't know if it's a good idea to start a new project and start recording at the same time, you can use the `POST /project` to start one and then call another API to start recording, so I'm thinking:
```js
chrome.runtime.sendMessage("mooikfkahbdckldjjndioackbalphokd", {
uri: "/record/session",
verb: "post",
payload: { url: 'the url to start from, if empty will use the url that the IDE has, or the IDE will show a dialog to give one' }
}, res => {
 // boolean recording was started or not
});
});
```
```js
chrome.runtime.sendMessage("mooikfkahbdckldjjndioackbalphokd", {
uri: "/record/session",
verb: "delete",
}, res => {
 // boolean recording was stopped or not
});
});
```

**Comment by ricardomoreirab** [comment]
Any progress? I was looking for this feature and found this issue here, maybe i can help with the implementation.

**Comment by corevo** [comment]
It was already implemented recently by a kind group of people, I think I merged that PR last week.

You can look into it, maybe it solves your use case, otherwise we can improve on it.

Since it was merged I'm closing.

**Comment by ricardomoreirab** [comment]
Thanks! i will check it out.

**Comment by ricardomoreirab** [comment]
I've seen the pull request, the item 1 is contemplated, now you can make a post to /project and it will open the IDE and create a project from API call, but i think the item 2 (recording controls) was still not implemented, maybe we can improve on it, let me know if you think its a good idea.
